### ISSUE TITLE
wget https://gitee.com/open-v2x/docs/repository/archive/master.zip  会出现timeout 

### ISSUE THREAD

**Issue by likai99c** [open-v2x/docs#28]
## Describe the bug
[quick_install_guide](https://github.com/open-v2x/docs/blob/albany/src/v2x-quick-install.md) 文档中，在gitee上获取zip会timeout, 因为gitee上会有二次验证，导致无法下载
$ wget https://gitee.com/open-v2x/docs/repository/archive/master.zip
--2022-08-05 17:49:49--  https://gitee.com/open-v2x/docs/repository/archive/master.zip
Resolving gitee.com (gitee.com)... 212.64.63.190, 212.64.63.215
Connecting to gitee.com (gitee.com)|212.64.63.190|:443... failed: Connection timed out.
Connecting to gitee.com (gitee.com)|212.64.63.215|:443... failed: Connection timed out.

**Comment by wu-wenxiang** [comment]
无法重现

在 master 中，我们为了缩小安装包，也转到了 Aliyun OSS 下载： wget https://openv2x.oss-ap-southeast-1.aliyuncs.com/deploy/openv2x-aio-albany.tar.gz，所以应该不存在此问题了
