### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by sunhr0503** [open-v2x/docs#88]
## Describe the bug

使用以下信息无法成功登录OpenV2X 路侧设备管理平台
用户名：admin
密    码：dandelion 

## To Reproduce

1. 进入
http://{localhost}:80/user/login
2. 输入
用户名：admin
密    码：dandelion 
3. 点击登录
4. 登录按钮变灰，等待加载
5. 没有提示，登录按钮变亮，并没有登陆成功（无提示）

## Expected behavior

正常登录并看到管理平台的内容

## Log Information

If applicable, add more detailed log information to help explain your problem.

## Desktop (please complete the following information):

- OS: windows & centos7
- Browser: edge & google-chrome --no-sandbox
- Version: edge:105.0.1343.42  & google-chrome105.0.5195.125

**Comment by wu-wenxiang** [comment]
目前，master 和 albany 分支都未能重现问题。
请帮忙说一下你用的 openv2x 版本。
把完整的安装过程（具体命令，环境变量配置）写一下。

**Comment by wu-wenxiang** [comment]
长时间没有更新，关闭此 issue
