### ISSUE TITLE
beihai 版本功能列表

### ISSUE THREAD

**Issue by lin-fuyu** [open-v2x/docs#99]
**加粗** 表示新增功能

### 设备管理平台

1. RSU 设备管理
2. 摄像头设备管理
3. 毫米波雷达设备管理
4. MAP 配置
5. RSU 信息上报、日志下发配置
6. 边缘站点配置
7. 事件管理 - 路侧单元信息 RSI
8. 事件管理 - 路侧单元消息 RSM
9. 事件管理 - 逆向超车预警
10. **事件管理 - 弱势交通参与者碰撞预警**
11. **事件管理 - 交叉路口碰撞预警**
12. **事件管理 - 感知数据共享**
13. **事件管理 - 协作式变道**
14. **信号灯设备管理**
15. **激光雷达设备管理**

### 云控中心

1. RSU 设备在线率
2. 摄像头设备在线率
3. 毫米波雷达设备在线率
4. **激光雷达设备在线率**
5. **信号灯设备在线率**
6. **摄像头视频流接入**
7. **激光雷达数据流接入**

**Comment by wu-wenxiang** [comment]
LGTM
